#!/usr/bin/env -S uv run --with 'fonttools[woff]' --with brotli --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["fonttools[woff]", "brotli"]
# ///
"""Regenerate the plan viewer's embedded @font-face blocks.

The rendered `plan.html` is self-contained: it fetches nothing, so its fonts
ship as `data:` URIs inside `src/plan/assets/plan.css` (a contract asserted by
`render.rs`'s `document_structure` test). That makes the stylesheet's first
~100 KB an opaque base64 blob, so this script is the audit trail: it says
exactly which upstream files those bytes came from and what was done to them.

What it does, per face:

  1. downloads Google Fonts' own `latin` subset of the variable font,
  2. pins/limits the variation axes (see FACES) so the payload only carries
     the weights the stylesheet actually asks for,
  3. re-compresses to woff2 and emits an `@font-face` block with the font
     inlined as base64.

Newsreader carries an optical-size axis (`opsz`, 6-72). The stylesheet only
ever sets one size regime, so pinning `opsz` to 16 drops well over half the
file with no visible change. Both families are SIL OFL 1.1 (see
`vendored/sources.toml`), which permits redistribution including embedding.

Usage:

    tools/build-plan-fonts.py            # print the blocks to stdout
    tools/build-plan-fonts.py --write    # splice them into plan.css in place

`--write` replaces everything between the FONT_BEGIN/FONT_END markers in
plan.css and leaves the rest of the file untouched.
"""

from __future__ import annotations

import argparse
import base64
import io
import pathlib
import sys
import urllib.request

from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

CSS_PATH = pathlib.Path(__file__).resolve().parent.parent / "src/plan/assets/plan.css"

BEGIN = "/* FONT_BEGIN — generated by tools/build-plan-fonts.py; do not hand-edit */"
END = "/* FONT_END */"

# Upstream `latin`-subset URLs, resolved from the Google Fonts CSS API at the
# versions below. Pinned by full URL on purpose: the hashed filename IS the
# version, so a silent upstream reflow can't change these bytes underneath us.
# Re-resolve with:
#   curl 'https://fonts.googleapis.com/css2?family=Newsreader:ital,opsz,wght@0,6..72,200..800;1,6..72,200..800&family=JetBrains+Mono:wght@100..800&display=swap'
FACES = [
    {
        "family": "Newsreader",
        "style": "normal",
        # The page sets 300 (the big phase numerals) through 600 (headings,
        # `<strong>`). Keeping 300 costs ~13 KB over a 400 floor and is what
        # makes the numerals read as light rules rather than bold labels.
        "axes": {"opsz": 16, "wght": (300, 600)},
        "weight": "300 600",
        "url": "https://fonts.gstatic.com/s/newsreader/v26/cY9AfjOCX1hbuyalUrK4397yjIJFJpc.woff2",
    },
    {
        "family": "Newsreader",
        "style": "italic",
        # Italic only ever carries markdown `*emphasis*`, which is always body
        # weight — pinning to a single 400 instance halves the payload. Emphasis
        # inside a heading synthesizes, which is rare enough to be worth 19 KB.
        "axes": {"opsz": 16, "wght": 400},
        "weight": "400",
        "url": "https://fonts.gstatic.com/s/newsreader/v26/cY9CfjOCX1hbuyalUrK439vCjohCBJWxZA.woff2",
    },
    {
        "family": "JetBrains Mono",
        "style": "normal",
        # Labels, badges, and numerals: regular through semibold. Nothing goes
        # heavier — at 11 px uppercase with wide tracking, 600 and 700 are
        # indistinguishable, so the extra weight is payload nobody sees.
        "axes": {"wght": (400, 600)},
        "weight": "400 600",
        "url": "https://fonts.gstatic.com/s/jetbrainsmono/v24/tDbV2o-flEEny0FZhsfKu5WU4xD7OwGtT0rU.woff2",
    },
    # No JetBrains Mono italic: nothing on the page sets monospace emphasis
    # (markdown can't nest `<em>` inside a code span), so it would be ~16 KB
    # of payload no reader ever sees.
    #
    # The vibe theme swaps all three voices. Bricolage Grotesque reads the
    # prose (its optical size pinned like Newsreader's, its width pinned to
    # normal), Space Mono says what the page says about it, Bungee sets the
    # display moments: the title, the numerals, the stats. All SIL OFL 1.1.
    # Re-resolve with:
    #   curl -A 'Mozilla/5.0 (Macintosh) Chrome/130' 'https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wdth,wght@12..96,75..100,200..800&family=Space+Mono:ital,wght@0,400;0,700;1,400&family=Bungee&display=swap'
    {
        "family": "Bricolage Grotesque",
        "style": "normal",
        "axes": {"opsz": 16, "wdth": 100, "wght": (400, 700)},
        "weight": "400 700",
        "url": "https://fonts.gstatic.com/s/bricolagegrotesque/v9/3y996as8bTXq_nANBjzKo3IeZx8z6up5L-iNGfyOPPs.woff2",
    },
    {
        "family": "Space Mono",
        "style": "normal",
        # A static family: two instances, no axes to pin.
        "axes": {},
        "weight": "400",
        "url": "https://fonts.gstatic.com/s/spacemono/v17/i7dPIFZifjKcF5UAWdDRYEF8RXi4EwQ.woff2",
    },
    {
        "family": "Space Mono",
        "style": "normal",
        "axes": {},
        "weight": "700",
        "url": "https://fonts.gstatic.com/s/spacemono/v17/i7dMIFZifjKcF5UAWdDRaPpZUFWaHi6WZ3Q.woff2",
    },
    {
        "family": "Bungee",
        "style": "normal",
        "axes": {},
        "weight": "400",
        "url": "https://fonts.gstatic.com/s/bungee/v17/N0bU2SZBIuF2PU_0DXR1C9zfmQ.woff2",
    },
]


def build_face(face: dict) -> str:
    req = urllib.request.Request(face["url"], headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req) as resp:
        raw = resp.read()

    font = TTFont(io.BytesIO(raw))
    if face["axes"]:
        instancer.instantiateVariableFont(font, face["axes"], inplace=True, updateFontNames=False)
    out = io.BytesIO()
    font.flavor = "woff2"
    font.save(out)
    payload = out.getvalue()

    b64 = base64.b64encode(payload).decode("ascii")
    print(
        f"  {face['family']} {face['style']}: {len(raw):,} -> {len(payload):,} bytes woff2",
        file=sys.stderr,
    )
    return (
        "@font-face {\n"
        f"  font-family: \"{face['family']}\";\n"
        f"  font-style: {face['style']};\n"
        f"  font-weight: {face['weight']};\n"
        "  font-display: swap;\n"
        f'  src: url("data:font/woff2;base64,{b64}") format("woff2");\n'
        "}"
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true", help="splice into plan.css in place")
    args = ap.parse_args()

    blocks = "\n\n".join(build_face(f) for f in FACES)
    section = f"{BEGIN}\n\n{blocks}\n\n{END}"

    if not args.write:
        print(section)
        return 0

    css = CSS_PATH.read_text()
    start, end = css.find(BEGIN), css.find(END)
    if start < 0 or end < 0:
        print(f"error: FONT_BEGIN/FONT_END markers not found in {CSS_PATH}", file=sys.stderr)
        return 1
    CSS_PATH.write_text(css[:start] + section + css[end + len(END) :])
    print(f"wrote {CSS_PATH} ({len(section):,} bytes of font section)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
